# Generated by Django 2.2.2 on 2019-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='0', max_length=1000)),
                ('answer', models.CharField(default='0', max_length=1000)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
