# Generated by Django 2.2.2 on 2019-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
