# Generated by Django 2.2.2 on 2019-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstn', '0002_auto_20190823_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default='0', max_length=100)),
            ],
            options={
                'db_table': 'sets',
            },
        ),
    ]
