# Generated by Django 2.2.2 on 2019-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstn', '0003_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='sid',
            field=models.IntegerField(default=0),
        ),
    ]
